Update Docker tags and versioning

diff --git a/.github/workflows/build-and-push-dev.yaml b/.github/workflows/build-and-push-dev.yaml
--- a/.github/workflows/build-and-push-dev.yaml
+++ b/.github/workflows/build-and-push-dev.yaml
@@ -117,24 +117,44 @@ jobs:
           cache-to: |
             type=registry,ref=${{ secrets.DOCKERHUB_NAMESPACE }}/docker-cache:buildcache.pihole-unbound.dev,mode=max
       -
-        name: Version code
-        id: version_code_check
+        name: Pi-hole version code
+        id: pihole_version_code_check
         run: |
           CHECK_VERSION_CODE=$(curl -s https://registry.hub.docker.com/v2/repositories/pihole/pihole/tags/dev | grep -oP '"tag_last_pushed":"\K[^"]+' | tail -1 | cut -c 1-9 | sed 's/-/./g')
           echo "New Version: $CHECK_VERSION_CODE"
+          echo VERSION_CODE=$CHECK_VERSION_CODE >> $GITHUB_OUTPUT
+      -
+        name: Unbound version code
+        id: unbound_version_code_check
+        run: |
+          function validate_version() {
+            local version="$1"
+            if [[ ! "$version" =~ ^[0-9]{1}\.[0-9]{2}\.[0-9]{1}$ ]]; then
+              echo "Error invalid version format: $version"
+              exit 1
+            fi
+          }
+          
+          CHECK_VERSION_CODE=$(curl -s https://api.github.com/repos/NLnetLabs/unbound/releases/latest | grep '"name"' | awk -F'"' '{print $4}' | cut -d' ' -f 2)
+          echo "Unbound Version: $CHECK_VERSION_CODE"
+          validate_version "$CHECK_VERSION_CODE"
           echo VERSION_CODE=$CHECK_VERSION_CODE >> $GITHUB_OUTPUT
       -
         name: Create release
         uses: svenstaro/upload-release-action@v2
         with:
           body: |
-            ## What's Changed (Docker Image dev-${{ steps.version_code_check.outputs.VERSION_CODE }})
+            ## Versions
+            Pi-hole: `${{ steps.pihole_version_code_check.outputs.VERSION_CODE }}`
+            Unbound: `${{ steps.unbound_version_code_check.outputs.VERSION_CODE }}`
+            
+            ## What's Changed (Docker Image dev-${{ steps.pihole_version_code_check.outputs.VERSION_CODE }})
             * Check Pi-hole Docker detailed changelog [here.](https://github.com/pi-hole/docker-pi-hole/commits/dev/)
-            * Check Unbound detailed changelog [here.](https://github.com/NLnetLabs/unbound/releases/latest)
+            * Check Unbound detailed changelog [here.](https://github.com/NLnetLabs/unbound/releases/tag/${{ steps.unbound_version_code_check.outputs.VERSION_CODE }})
           repo_token: ${{ secrets.GITHUB_TOKEN }}
           file: ./digest/digest_base_dev
-          release_name: dev-${{ steps.version_code_check.outputs.VERSION_CODE }}
-          tag: dev-${{ steps.version_code_check.outputs.VERSION_CODE }}
+          release_name: dev-${{ steps.pihole_version_code_check.outputs.VERSION_CODE }}
+          tag: dev-${{ steps.pihole_version_code_check.outputs.VERSION_CODE }}
           prerelease: true
           overwrite: true
       -
diff --git a/.github/workflows/build-and-push-latest.yaml b/.github/workflows/build-and-push-latest.yaml
--- a/.github/workflows/build-and-push-latest.yaml
+++ b/.github/workflows/build-and-push-latest.yaml
@@ -88,8 +88,8 @@ jobs:
         with:
           ref: main
       -
-        name: Version code
-        id: version_code_check
+        name: Pi-hole version code
+        id: pihole_version_code_check
         run: |
           function validate_version() {
             local version="$1"
@@ -100,7 +100,23 @@ jobs:
           }
           
           CHECK_VERSION_CODE=$(curl -s https://api.github.com/repos/pi-hole/docker-pi-hole/releases/latest | grep "name" | cut -d'"' -f 4 | tail -n 1)
-          echo "New Version: $CHECK_VERSION_CODE"
+          echo "Pi-hole Version: $CHECK_VERSION_CODE"
+          validate_version "$CHECK_VERSION_CODE"
+          echo VERSION_CODE=$CHECK_VERSION_CODE >> $GITHUB_OUTPUT
+      -
+        name: Unbound version code
+        id: unbound_version_code_check
+        run: |
+          function validate_version() {
+            local version="$1"
+            if [[ ! "$version" =~ ^[0-9]{1}\.[0-9]{2}\.[0-9]{1}$ ]]; then
+              echo "Error invalid version format: $version"
+              exit 1
+            fi
+          }
+          
+          CHECK_VERSION_CODE=$(curl -s https://api.github.com/repos/NLnetLabs/unbound/releases/latest | grep '"name"' | awk -F'"' '{print $4}' | cut -d' ' -f 2)
+          echo "Unbound Version: $CHECK_VERSION_CODE"
           validate_version "$CHECK_VERSION_CODE"
           echo VERSION_CODE=$CHECK_VERSION_CODE >> $GITHUB_OUTPUT
       -
@@ -119,7 +135,7 @@ jobs:
           flavor: |
             latest=true
           tags: |
-            type=raw,value=${{ steps.version_code_check.outputs.VERSION_CODE }}
+            type=raw,value=${{ steps.pihole_version_code_check.outputs.VERSION_CODE }}-${{ steps.unbound_version_code_check.outputs.VERSION_CODE }}
       -
         name: Login to DockerHub
         uses: docker/login-action@v3
@@ -145,13 +161,23 @@ jobs:
         uses: svenstaro/upload-release-action@v2
         with:
           body: |
-            ## What's Changed (Docker Image v${{ steps.version_code_check.outputs.VERSION_CODE }})
-            * Check Pi-hole Docker detailed changelog [here.](https://github.com/pi-hole/docker-pi-hole/releases/tag/${{ steps.version_code_check.outputs.VERSION_CODE }})
-            * Check Unbound detailed changelog [here.](https://github.com/NLnetLabs/unbound/releases/latest)
+            ## Versions
+            Pi-hole: `${{ steps.pihole_version_code_check.outputs.VERSION_CODE }}`
+            Unbound: `${{ steps.unbound_version_code_check.outputs.VERSION_CODE }}`
+            
+            ## Docker Tags
+            | Tag | Type | Description |
+            | :---: | :---: | :---: |
+            | `latest` | Stable | Always latest release |
+            | `${{ steps.pihole_version_code_check.outputs.VERSION_CODE }}-${{ steps.unbound_version_code_check.outputs.VERSION_CODE }}` | Date-based release [Pi-hole Version-Unbound Version] |
+            
+            ## What's Changed (Docker Image v${{ steps.pihole_version_code_check.outputs.VERSION_CODE }}-${{ steps.unbound_version_code_check.outputs.VERSION_CODE }})
+            * Check Pi-hole Docker detailed changelog [here.](https://github.com/pi-hole/docker-pi-hole/releases/tag/${{ steps.pihole_version_code_check.outputs.VERSION_CODE }})
+            * Check Unbound detailed changelog [here.](https://github.com/NLnetLabs/unbound/releases/tag/${{ steps.unbound_version_code_check.outputs.VERSION_CODE }})
           repo_token: ${{ secrets.GITHUB_TOKEN }}
           file: ./digest/digest_base_latest
-          release_name: ${{ steps.version_code_check.outputs.VERSION_CODE }}
-          tag: ${{ steps.version_code_check.outputs.VERSION_CODE }}
+          release_name: ${{ steps.pihole_version_code_check.outputs.VERSION_CODE }}-${{ steps.unbound_version_code_check.outputs.VERSION_CODE }}
+          tag: ${{ steps.pihole_version_code_check.outputs.VERSION_CODE }}-${{ steps.unbound_version_code_check.outputs.VERSION_CODE }}
           make_latest: true
           overwrite: true
       -
