Fix build error 3

diff --git a/.github/workflows/build-and-push-dev-v6.yaml b/.github/workflows/build-and-push-dev-v6.yaml
--- a/.github/workflows/build-and-push-dev-v6.yaml
+++ b/.github/workflows/build-and-push-dev-v6.yaml
@@ -81,6 +81,29 @@ jobs:
         with:
           ref: main
       -
+        name: Pi-hole version code
+        id: pihole_version_code_check
+        run: |
+          CHECK_VERSION_CODE=$(curl -s https://registry.hub.docker.com/v2/repositories/pihole/pihole/tags/development | grep -oP '"tag_last_pushed":"\K[^"]+' | tail -1 | cut -c 1-9 | sed 's/-/./g')
+          echo "New Version: $CHECK_VERSION_CODE"
+          echo VERSION_CODE=$CHECK_VERSION_CODE >> $GITHUB_OUTPUT
+      -
+        name: Unbound version code
+        id: unbound_version_code_check
+        run: |
+          function validate_version() {
+            local version="$1"
+            if [[ ! "$version" =~ ^[0-9]{1}\.[0-9]{2}\.[0-9]{1}$ ]]; then
+              echo "Error invalid version format: $version"
+              exit 1
+            fi
+          }
+          
+          CHECK_VERSION_CODE=$(curl -s https://api.github.com/repos/NLnetLabs/unbound/releases/latest | grep '"name"' | awk -F'"' '{print $4}' | cut -d' ' -f 2)
+          echo "Unbound Version: $CHECK_VERSION_CODE"
+          validate_version "$CHECK_VERSION_CODE"
+          echo VERSION_CODE=$CHECK_VERSION_CODE >> $GITHUB_OUTPUT
+      -
         name: Set up QEMU
         uses: docker/setup-qemu-action@v3
       -
@@ -106,15 +129,13 @@ jobs:
       -
         name: Build and push
         uses: docker/build-push-action@v6
-        env:
-          UNBOUND_VERSION_CODE: ${{ steps.unbound_version_code_check.outputs.VERSION_CODE }}
         with:
           context: ./
           file: ./Dockerfile-Dev-V6
           platforms: linux/amd64, linux/arm64, linux/arm/v7, linux/arm/v6
-          bbuild-args: |
+          build-args: |
             BASE_IMG_TAG=development
-            UNBOUND_VERSION_CODE=UNBOUND_VERSION_CODE
+            UNBOUND_VERSION_CODE=${{ steps.unbound_version_code_check.outputs.VERSION_CODE }}
           push: true
           tags: ${{ steps.meta.outputs.tags }}
           labels: ${{ steps.meta.outputs.labels }}
@@ -122,29 +143,6 @@ jobs:
             type=registry,ref=${{ secrets.DOCKERHUB_NAMESPACE }}/docker-cache:buildcache.pihole-unbound.development
           cache-to: |
             type=registry,ref=${{ secrets.DOCKERHUB_NAMESPACE }}/docker-cache:buildcache.pihole-unbound.development,mode=max
-      -
-        name: Pi-hole version code
-        id: pihole_version_code_check
-        run: |
-          CHECK_VERSION_CODE=$(curl -s https://registry.hub.docker.com/v2/repositories/pihole/pihole/tags/development | grep -oP '"tag_last_pushed":"\K[^"]+' | tail -1 | cut -c 1-9 | sed 's/-/./g')
-          echo "New Version: $CHECK_VERSION_CODE"
-          echo VERSION_CODE=$CHECK_VERSION_CODE >> $GITHUB_OUTPUT
-      -
-        name: Unbound version code
-        id: unbound_version_code_check
-        run: |
-          function validate_version() {
-            local version="$1"
-            if [[ ! "$version" =~ ^[0-9]{1}\.[0-9]{2}\.[0-9]{1}$ ]]; then
-              echo "Error invalid version format: $version"
-              exit 1
-            fi
-          }
-          
-          CHECK_VERSION_CODE=$(curl -s https://api.github.com/repos/NLnetLabs/unbound/releases/latest | grep '"name"' | awk -F'"' '{print $4}' | cut -d' ' -f 2)
-          echo "Unbound Version: $CHECK_VERSION_CODE"
-          validate_version "$CHECK_VERSION_CODE"
-          echo VERSION_CODE=$CHECK_VERSION_CODE >> $GITHUB_OUTPUT
       -
         name: Create release
         uses: svenstaro/upload-release-action@v2
